import { Link } from "react-router-dom";
import { Section, SubSection, CodeBlock, InlineCode, Callout } from "./Section";

export function DocsAgentIdentityContent() {
    return (
        <>
            <Section title="What an agent's identity is">
                <p>
                    Every agent installation has exactly one identity, made of
                    two parts:
                </p>
                <ul className="list-disc pl-5 space-y-1.5">
                    <li>
                        <strong>Installation UUID</strong> - a fresh, immutable
                        UUID generated by the installer. It names the instance
                        directory, the keystore key, and the service, so
                        multiple agents on one machine never collide. It is an{" "}
                        <strong>identifier, not a secret</strong>.
                    </li>
                    <li>
                        <strong>RSA-2048 keypair</strong> - the private key never
                        leaves the OS keystore; only its public half is ever
                        transmitted. Holding the private key is what lets the
                        agent prove who it is.
                    </li>
                </ul>
                <p>
                    The backend stores the public key and a fingerprint of it;
                    it never receives the private key, and the UUID is matched
                    to servers rather than trusted as a credential. See{" "}
                    <Link
                        to="/docs/agent-security"
                        className="text-primary hover:underline"
                    >
                        Agent Security
                    </Link>{" "}
                    for how these parts are used to authenticate.
                </p>
            </Section>

            <Section title="Key storage by platform">
                <p>
                    The key store is an abstraction (the{" "}
                    <InlineCode>KeyStore</InlineCode> interface in{" "}
                    <InlineCode>keystore.go</InlineCode>) with two platform
                    implementations selected at build time. Higher-level code
                    never knows where the key lives.
                </p>
                <SubSection title="Windows - NCrypt / CNG">
                    <p>
                        The key is stored via the native{" "}
                        <InlineCode>ncrypt.dll</InlineCode> API in the{" "}
                        <strong>per-user key store of the service account</strong>{" "}
                        (LocalSystem for the installed service). The agent
                        prefers the TPM-backed{" "}
                        <InlineCode>Microsoft Platform Crypto Provider</InlineCode>{" "}
                        when it can create keys (a real TPM present), falling
                        back to the{" "}
                        <InlineCode>Microsoft Software Key Storage Provider</InlineCode>
                        . Key name:{" "}
                        <InlineCode>MonitorAgentIdentity-&lt;uuid&gt;</InlineCode>
                        . The agent never calls{" "}
                        <InlineCode>NCryptExportKey</InlineCode> for the private
                        key, so even a software key is never exported by the
                        application; TPM keys are additionally non-exportable at
                        the hardware level.
                    </p>
                </SubSection>
                <SubSection title="Linux - protected file">
                    <p>
                        The key is a PKCS#8 PEM file at{" "}
                        <InlineCode>/var/lib/monitor-agent/identity-&lt;uuid&gt;.pem</InlineCode>
                        , owned by the <InlineCode>monitor</InlineCode> service
                        account with mode <InlineCode>0600</InlineCode>. It sits{" "}
                        <strong>outside</strong> the instance configuration
                        directory, which is itself service-owned.
                    </p>
                    <Callout type="warning">
                        A 0600 file is only as strong as OS file permissions -
                        anyone with root or the service account can read it, and
                        it is exportable by design. A TPM- or kernel-backed
                        signer is the stronger option; the Linux keystore
                        documents that replacing{" "}
                        <InlineCode>keystore_linux.go</InlineCode> with a
                        pkcs11/tpm2-backed store is all that would be needed.
                    </Callout>
                </SubSection>
            </Section>

            <Section title="The public half and fingerprint">
                <p>
                    The public key is exported as PKIX SubjectPublicKeyInfo
                    (SPKI) DER:
                </p>
                <ul className="list-disc pl-5 space-y-1.5">
                    <li>
                        <strong>Base64-encoded</strong> and sent during
                        registration; the backend stores it in{" "}
                        <InlineCode>agents.public_key</InlineCode>.
                    </li>
                    <li>
                        <strong>SHA-256 hash</strong> of the SPKI DER, hex
                        encoded, stored in{" "}
                        <InlineCode>agents.public_key_hash</InlineCode>. This is
                        a fingerprint used to start the challenge-response
                        handshake - a stable identifier, <em>not</em> a
                        credential.
                    </li>
                    <li>
                        <strong>Installation UUID</strong> is stored in{" "}
                        <InlineCode>agents.installation_uuid</InlineCode>{" "}
                        (unique), which the backend uses to find-or-create the
                        agent on registration.
                    </li>
                </ul>
                <CodeBlock>{`public_key       = base64( SPKI_DER(public_key) )   # sent to backend
public_key_hash  = hex( sha256( SPKI_DER ) )          # fingerprint
installation_id  = <uuid>                             # identifier, not secret`}</CodeBlock>
            </Section>

            <Section title="Where the key never lives">
                <ul className="list-disc pl-5 space-y-1.5">
                    <li>
                        <strong>Not in config.json</strong> - the bootstrap
                        config holds only non-secrets (server URL, version,
                        installation ID) plus a one-time provision token that is
                        stripped after registration.
                    </li>
                    <li>
                        <strong>Not in logs</strong> - crash/panic reporting
                        explicitly excludes the private key, signatures, and
                        credentials.
                    </li>
                    <li>
                        <strong>Not in the binary directory</strong> - Program
                        Files / /opt is read-only at runtime.
                    </li>
                    <li>
                        <strong>Not in the database</strong> - the backend only
                        ever sees the public key and its hash.
                    </li>
                </ul>
            </Section>

            <Section title="Identity lifecycle">
                <ol className="list-decimal pl-5 space-y-1.5">
                    <li>
                        <strong>Created</strong> - on first run,{" "}
                        <InlineCode>GetOrCreateKey</InlineCode> generates the
                        keypair in the OS keystore (the installer pre-checks
                        with <InlineCode>-has-key</InlineCode> to avoid
                        collisions).
                    </li>
                    <li>
                        <strong>Used</strong> - the private key signs each
                        authentication challenge; the public key verifies it on
                        the backend.
                    </li>
                    <li>
                        <strong>Survives everything except uninstall</strong> -
                        restart, reboot, and binary updates do not touch it. The
                        key is deleted only during uninstall, and only by the
                        service account (via the marker flow), because that is
                        the sole principal allowed to access it.
                    </li>
                </ol>
                <p>
                    A lost key means the agent can no longer authenticate. The
                    fix is a reinstall, which mints a fresh identity and a fresh
                    registration.
                </p>
            </Section>
        </>
    );
}