/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>[];
                    };
                };
                401: components["responses"]["AuthenticationException"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description `ServerData` */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerData"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            error: "Server not found.";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            /** @constant */
                            message: "Metrics recorded.";
                        };
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            error: "Unauthorized or invalid server ID.";
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client.index"];
        put?: never;
        post: operations["client.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client.show"];
        put: operations["client.update"];
        post?: never;
        delete: operations["client.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["client.servers"];
        put?: never;
        post: operations["client.initializeServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard.stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard.actions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/actions/completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard.completed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/actions/{actionId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dashboard.claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/actions/{actionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dashboard.updateStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["jwtAuth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["jwtAuth.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["jwtAuth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["jwtAuth.logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jwtAuth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["server.index"];
        put?: never;
        post: operations["server.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/servers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["server.show"];
        put: operations["server.update"];
        post?: never;
        delete: operations["server.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}/servers/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server.installServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["session.revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/logout-all-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["session.revokeAllOthers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionUuid}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["session.permanentDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/security-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session.securityActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/active-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["session.activeSessionsCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/profile-picture/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploads.profile-picture.signature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/client-banner/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploads.client-banner.signature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.index"];
        put?: never;
        post: operations["users.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.show"];
        put: operations["users.update"];
        post?: never;
        delete: operations["users.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemData */
        ActionItemData: {
            id: number;
            action_type: string;
            message: string;
            severity: string;
            server_id?: number | null;
            client_id?: number | null;
            client_name?: string | null;
            server_name?: string | null;
            assigned_to?: number | null;
            assigned_to_name?: string | null;
            status: string;
        };
        /** AuthAuditLogResource */
        AuthAuditLogResource: {
            id: number;
            user_id: number | null;
            session_uuid: string | null;
            event_type: string;
            ip_address: string | null;
            user_agent: string | null;
            metadata: unknown[] | null;
            created_at: string;
            created_at_timestamp: string;
        };
        /** AuthUserData */
        AuthUserData: {
            id: number;
            first_name: string;
            last_name: string;
            email: string;
            username: string;
            contact_number: string;
            last_login?: string | null;
            profile_picture_url: string;
            role: "Admin" | "User" | "SecOps";
        };
        /** ClientData */
        ClientData: {
            id: number;
            name: string;
            description: string;
            location: string;
            email: string;
            contact_number: string;
            banner_image_path?: string | null;
            banner_image_url: string;
            banner_image_public_id?: string | null;
            servers_count: number;
            created_at: string;
            updated_at: string;
        };
        /** DashboardStatsData */
        DashboardStatsData: {
            total_clients: number;
            total_servers: number;
            online_count: number;
            warning_count: number;
            offline_count: number;
            top_usage_cpu: {
                server_id: number;
                server_name: string;
                client_name: string;
                value: number;
            }[];
            top_usage_memory: {
                server_id: number;
                server_name: string;
                client_name: string;
                value: number;
            }[];
            top_usage_disk: {
                server_id: number;
                server_name: string;
                client_name: string;
                value: number;
            }[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            remember?: boolean;
        };
        /** Server */
        Server: {
            id: number;
            client_id: number;
            server_name: string;
            device_name: string;
            internal_ip: string;
            external_ip: string;
            ssh_username: string | null;
            api_key: string;
            cpu_cores: number | null;
            ram: number | null;
            operating_system: string | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** ServerData */
        ServerData: {
            server_name: string;
            /** Format: ipv4 */
            internal_ip: string;
            device_name?: string | null;
            external_ip?: string | null;
            ssh_username?: string | null;
            ssh_password?: string | null;
            cpu_cores?: number | null;
            ram?: number | null;
            operating_system?: string | null;
            id?: number | null;
            client_id?: number | null;
            client_name?: string | null;
            stats?: string[];
        };
        /** SessionResource */
        SessionResource: {
            session_uuid: string;
            device_name: string;
            device_type: string;
            browser: string;
            operating_system: string;
            ip_address: string;
            remember_me: string;
            last_activity_at: string;
            last_activity_at_timestamp: string;
            created_at: string;
            created_at_timestamp: string;
            current_session: boolean;
            status: string;
            compromised: string;
            compromised_at: string;
            compromised_at_timestamp: string;
            compromise_reason: string;
            revoked_at: string;
            revoked_at_timestamp: string;
        };
        /** UploadSignatureData */
        UploadSignatureData: {
            cloud_name: string;
            api_key: string;
            timestamp: number;
            folder: string;
            signature: string;
        };
        /** UploadSignatureRequest */
        UploadSignatureRequest: {
            /** @enum {string} */
            folder?: "profile_pictures" | "client_banner_images";
        };
        /** UserData */
        UserData: {
            id: number;
            first_name: string;
            last_name: string;
            email: string;
            username: string;
            contact_number: string;
            last_login?: string | null;
            profile_picture_url: string;
            status: string;
            role: "Admin" | "User" | "SecOps";
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "Admin" | "User" | "SecOps";
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "client.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientData"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    location: string;
                    email: string;
                    contact_number: string;
                    description?: string | null;
                    banner_image?: Record<string, never> | null;
                    cloudinary_url?: string | null;
                    cloudinary_public_id?: string | null;
                };
            };
        };
        responses: {
            /** @description `ClientData` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ClientData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    location: string;
                    email: string;
                    contact_number: string;
                    description?: string;
                    cloudinary_url?: string | null;
                    cloudinary_public_id?: string | null;
                };
            };
        };
        responses: {
            /** @description `ClientData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.servers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "client.initializeServer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `DashboardStatsData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemData"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemData"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.claim": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ActionItemData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "dashboard.updateStatus": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ActionItemData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "jwtAuth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "jwtAuth.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | string;
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "No refresh token provided.";
                    };
                };
            };
        };
    };
    "jwtAuth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Logged out successfully.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "jwtAuth.logoutAll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "All sessions logged out.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "jwtAuth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AuthUserData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        client_id: number;
                        server_name: string;
                        device_name: string;
                        internal_ip: string;
                        external_ip: string;
                        ssh_username: string | null;
                        cpu_cores: number | null;
                        ram: number | null;
                        operating_system: string | null;
                        created_at: string | "";
                        updated_at: string | "";
                    }[];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                    /** Format: ipv4 */
                    internal_ip: string;
                    device_name?: string | null;
                    external_ip?: string | null;
                    ssh_username?: string | null;
                    ssh_password?: string | null;
                    cpu_cores?: number | null;
                    ram?: number | null;
                    operating_system?: string | null;
                    id?: number | null;
                    client_id?: number | null;
                    client_name?: string | null;
                    stats?: string[];
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: components["schemas"]["Server"];
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        error: "Client not found.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: components["schemas"]["Server"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                    /** Format: ipv4 */
                    internal_ip: string;
                    device_name?: string | null;
                    external_ip?: string | null;
                    ssh_username?: string | null;
                    ssh_password?: string | null;
                    cpu_cores?: number | null;
                    ram?: number | null;
                    operating_system?: string | null;
                    id?: number | null;
                    client_id?: number | null;
                    client_name?: string | null;
                    stats?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: components["schemas"]["Server"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        data: components["schemas"]["Server"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "server.installServer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    server_name: string;
                    /** Format: ipv4 */
                    internal_ip: string;
                    device_name?: string | null;
                    external_ip?: string | null;
                    ssh_username?: string | null;
                    ssh_password?: string | null;
                    cpu_cores?: number | null;
                    ram?: number | null;
                    operating_system?: string | null;
                    id?: number | null;
                    client_id?: number | null;
                    client_name?: string | null;
                    stats?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "success";
                        log: {
                            wget: string;
                            install: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "error";
                        message: string;
                    };
                };
            };
        };
    };
    "session.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SessionResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "session.revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session revoked successfully.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Cannot revoke current session. Use logout instead.";
                    };
                };
            };
        };
    };
    "session.revokeAllOthers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "All other sessions logged out.";
                        revoked_count: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "session.permanentDelete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session deleted permanently.";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        message: "Session must be revoked before permanent deletion.";
                    } | {
                        /** @constant */
                        message: "Cannot delete current session.";
                    };
                };
            };
        };
    };
    "session.securityActivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthAuditLogResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "session.activeSessionsCount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        active_count: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "uploads.profile-picture.signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UploadSignatureRequest"];
            };
        };
        responses: {
            /** @description `UploadSignatureData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignatureData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "uploads.client-banner.signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UploadSignatureRequest"];
            };
        };
        responses: {
            /** @description `UploadSignatureData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSignatureData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "users.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"][];
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "users.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    first_name: string;
                    last_name: string;
                    /**
                     * Format: email
                     * @description Must be unique in `users`.
                     */
                    email: string;
                    /** @description Must be unique in `users`. */
                    contact_number: string;
                    /** @description Must be unique in `users`. */
                    username: string;
                    role_id: number;
                    /** @description Must be confirmed by a matching `_confirmation` field. */
                    password: string;
                    password_confirmation: string;
                    cloudinary_url?: string | null;
                    cloudinary_public_id?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "users.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    first_name?: string;
                    last_name?: string;
                    /** Format: email */
                    email?: string;
                    contact_number: string;
                    username?: string;
                    role_id?: number;
                    /** @description Must be confirmed by a matching `_confirmation` field. */
                    password?: string | null;
                    password_confirmation?: string | null;
                    cloudinary_url?: string | null;
                    cloudinary_public_id?: string | null;
                };
            };
        };
        responses: {
            /** @description `UserData` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user ID */
                user: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
