// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is automatically generated by scripts/generate-models.js

import type { components, operations } from "@/api/schema";

export type ActionItemData = components["schemas"]["ActionItemData"];
export type ActivityLog = components["schemas"]["ActivityLog"];
export type AuthUserData = components["schemas"]["AuthUserData"];
export type ClientData = components["schemas"]["ClientData"];
export type DashboardStatsData = components["schemas"]["DashboardStatsData"];
export type GlobalAlert = components["schemas"]["GlobalAlert"];
export type SecopsUserData = components["schemas"]["SecopsUserData"];
export type SecurityActivityData = components["schemas"]["SecurityActivityData"];
export type ServerData = components["schemas"]["ServerData"];
export type StatPointData = components["schemas"]["StatPointData"];
export type StoreUploadIntentRequest = components["schemas"]["StoreUploadIntentRequest"];
export type UpdateUserData = components["schemas"]["UpdateUserData"];
export type UploadPurpose = components["schemas"]["UploadPurpose"];
export type UserData = components["schemas"]["UserData"];

// --- Inlined Operation Payloads ---
export type ServerStorePayload = NonNullable<operations["server.store"]["requestBody"]>["content"]["application/json"];
export type ClientStorePayload = NonNullable<operations["client.store"]["requestBody"]>["content"]["multipart/form-data"];
export type ClientUpdatePayload = NonNullable<operations["client.update"]["requestBody"]>["content"]["application/json"];
export type ClientAddSecopPayload = NonNullable<operations["client.addSecop"]["requestBody"]>["content"]["application/json"];
export type GlobalAlertUpdatePayload = NonNullable<operations["globalAlert.update"]["requestBody"]>["content"]["application/json"];
export type JwtAuthLoginPayload = NonNullable<operations["jwtAuth.login"]["requestBody"]>["content"]["application/json"];
export type ServerUpdatePayload = NonNullable<operations["server.update"]["requestBody"]>["content"]["application/json"];
export type ServerUninstallServerPayload = NonNullable<operations["server.uninstallServer"]["requestBody"]>["content"]["application/json"];
export type ServerIngestStatsPayload = NonNullable<operations["server.ingestStats"]["requestBody"]>["content"]["application/json"];
export type ServerUpdateServerSpecsPayload = NonNullable<operations["server.updateServerSpecs"]["requestBody"]>["content"]["application/json"];
export type UploadIntentsStorePayload = NonNullable<operations["upload-intents.store"]["requestBody"]>["content"]["application/json"];
export type UsersStorePayload = NonNullable<operations["users.store"]["requestBody"]>["content"]["application/json"];
export type UsersUpdatePayload = NonNullable<operations["users.update"]["requestBody"]>["content"]["application/json"];
export type UserAddClientPayload = NonNullable<operations["user.addClient"]["requestBody"]>["content"]["application/json"];
