import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const apiJsonPath = path.resolve(__dirname, "../src/api/api.json");
const modelsPath = path.resolve(__dirname, "../src/types/models.ts");

if (!fs.existsSync(apiJsonPath)) {
    console.error("api.json not found. Run openapi generation first.");
    process.exit(1);
}

const apiJson = JSON.parse(fs.readFileSync(apiJsonPath, "utf8"));
const schemas = apiJson.components?.schemas || {};

let content = `// AUTO-GENERATED FILE. DO NOT EDIT.\n`;
content += `// This file is automatically generated by scripts/generate-models.js\n\n`;
content += `import type { components } from "@/api/schema";\n\n`;

for (const schemaName of Object.keys(schemas)) {
    // Strip "Data" from the end of the schema name if it exists (e.g. UserData -> User)
    const cleanName = schemaName.endsWith("Data")
        ? schemaName.replace(/Data$/, "")
        : schemaName;
    content += `export type ${cleanName} = components["schemas"]["${schemaName}"];\n`;
}

fs.mkdirSync(path.dirname(modelsPath), { recursive: true });
fs.writeFileSync(modelsPath, content);

console.log(
    `[SUCCESS] Generated models.ts with ${Object.keys(schemas).length} schema aliases.`,
);
