import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const apiJsonPath = path.resolve(__dirname, "../src/api/api.json");
const modelsPath = path.resolve(__dirname, "../src/types/models.ts");
const templateVarsPath = path.resolve(
    __dirname,
    "../src/components/node-config/nodes/templateVariables.ts",
);

if (!fs.existsSync(apiJsonPath)) {
    console.error("api.json not found. Run openapi generation first.");
    process.exit(1);
}

const apiJson = JSON.parse(fs.readFileSync(apiJsonPath, "utf8"));
const schemas = apiJson.components?.schemas || {};

// ── models.ts ──────────────────────────────────────────────────────────────

let content = `// AUTO-GENERATED FILE. DO NOT EDIT.\n`;
content += `// This file is automatically generated by scripts/generate-models.js\n\n`;
content += `import type { components, operations } from "@/api/schema";\n\n`;

for (const schemaName of Object.keys(schemas)) {
    // Keep exact schema name, e.g. UserData instead of stripping "Data"
    content += `export type ${schemaName} = components["schemas"]["${schemaName}"];\n`;
}

content += `\n// --- Inlined Operation Payloads ---\n`;

const apiPaths = apiJson.paths || {};
for (const [pathUrl, pathItem] of Object.entries(apiPaths)) {
    for (const [method, operation] of Object.entries(pathItem)) {
        if (!operation.operationId) continue;
        
        // Extract inline request bodies
        const requestBody = operation.requestBody;
        if (requestBody && requestBody.content) {
            const contentTypes = Object.keys(requestBody.content);
            if (contentTypes.length > 0) {
                const contentType = contentTypes[0]; // application/json, multipart/form-data, etc
                
                // e.g. "users.store" -> "UsersStorePayload"
                const nameParts = operation.operationId.split('.');
                const typeName = nameParts.map(p =>
                    p.split('-').map(sub => sub.charAt(0).toUpperCase() + sub.slice(1)).join('')
                ).join('') + 'Payload';
                
                content += `export type ${typeName} = NonNullable<operations["${operation.operationId}"]["requestBody"]>["content"]["${contentType}"];\n`;
            }
        }
    }
}

fs.mkdirSync(path.dirname(modelsPath), { recursive: true });
fs.writeFileSync(modelsPath, content);

console.log(
    `[SUCCESS] Generated models.ts with ${Object.keys(schemas).length} schemas and inlined payloads.`,
);

// ── templateVariables.ts ────────────────────────────────────────────────────

const SCHEMA_TO_VAR = [
    { schema: "ServerData",   prefix: "server",          group: "server" },
    { schema: "ClientData",   prefix: "server.client",   group: "client" },
    { schema: "StatPointData", prefix: "metric",         group: "metric" },
];

function snakeToTitle(s) {
    return s
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
}

const labels = [];

for (const { schema, prefix, group } of SCHEMA_TO_VAR) {
    const schemaObj = schemas[schema];
    if (!schemaObj?.properties) {
        console.warn(
            `[WARN] Schema "${schema}" not found or has no properties — skipping template variables for group "${group}".`,
        );
        continue;
    }

    for (const propName of Object.keys(schemaObj.properties)) {
        labels.push({
            key: `${prefix}.${propName}`,
            label: snakeToTitle(propName),
            group,
            description: `${snakeToTitle(propName)} (${schema})`,
        });
    }
}

const lines = [];
lines.push(`import type { components } from '@/api/schema';`);
lines.push(``);
lines.push(`type ServerData = components['schemas']['ServerData'];`);
lines.push(`type ClientData = components['schemas']['ClientData'];`);
lines.push(`type StatPointData = components['schemas']['StatPointData'];`);
lines.push(``);
lines.push(`type ServerVarKey = \`server.\${keyof ServerData & string}\`;`);
lines.push(`type ClientVarKey = \`server.client.\${keyof ClientData & string}\`;`);
lines.push(`type MetricVarKey = \`metric.\${keyof StatPointData & string}\`;`);
lines.push(``);
lines.push(`type TemplateVariableKey = ServerVarKey | ClientVarKey | MetricVarKey;`);
lines.push(``);
lines.push(`export interface TemplateVariable {`);
lines.push(`    key: TemplateVariableKey;`);
lines.push(`    label: string;`);
lines.push(`    group: 'server' | 'client' | 'metric';`);
lines.push(`    description: string;`);
lines.push(`}`);
lines.push(``);
lines.push(`const LABELS: Record<TemplateVariableKey, { label: string; group: TemplateVariable['group']; description: string }> = {`);

for (const { key, label, group, description } of labels) {
    // Pad keys for alignment
    const pad = Math.max(0, 32 - key.length - 2); // 2 for quotes
    lines.push(
        `    '${key}'${" ".repeat(pad)}: { label: '${label}', group: '${group}', description: '${description}' },`,
    );
}

lines.push(`};`);
lines.push(``);
lines.push(`export const TEMPLATE_VARIABLES: TemplateVariable[] = (Object.entries(LABELS) as [TemplateVariableKey, typeof LABELS[TemplateVariableKey]][]).map(`);
lines.push(`    ([key, meta]) => ({ key, ...meta }),`);
lines.push(`);`);
lines.push(``);
lines.push(`export function filterVariables(query: string): TemplateVariable[] {`);
lines.push(`    const q = query.toLowerCase();`);
lines.push(`    return TEMPLATE_VARIABLES.filter(`);
lines.push(`        (v) => v.key.toLowerCase().includes(q) || v.label.toLowerCase().includes(q),`);
lines.push(`    );`);
lines.push(`}`);
lines.push(``);

fs.mkdirSync(path.dirname(templateVarsPath), { recursive: true });
fs.writeFileSync(templateVarsPath, lines.join("\n"));

console.log(
    `[SUCCESS] Generated templateVariables.ts with ${labels.length} template variables.`,
);
