import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const apiJsonPath = path.resolve(__dirname, "../src/api/api.json");
const modelsPath = path.resolve(__dirname, "../src/types/models.ts");

if (!fs.existsSync(apiJsonPath)) {
    console.error("api.json not found. Run openapi generation first.");
    process.exit(1);
}

const apiJson = JSON.parse(fs.readFileSync(apiJsonPath, "utf8"));
const schemas = apiJson.components?.schemas || {};

let content = `// AUTO-GENERATED FILE. DO NOT EDIT.\n`;
content += `// This file is automatically generated by scripts/generate-models.js\n\n`;
content += `import type { components, operations } from "@/api/schema";\n\n`;

for (const schemaName of Object.keys(schemas)) {
    // Keep exact schema name, e.g. UserData instead of stripping "Data"
    content += `export type ${schemaName} = components["schemas"]["${schemaName}"];\n`;
}

content += `\n// --- Inlined Operation Payloads ---\n`;

const apiPaths = apiJson.paths || {};
for (const [pathUrl, pathItem] of Object.entries(apiPaths)) {
    for (const [method, operation] of Object.entries(pathItem)) {
        if (!operation.operationId) continue;
        
        // Extract inline request bodies
        const requestBody = operation.requestBody;
        if (requestBody && requestBody.content) {
            const contentTypes = Object.keys(requestBody.content);
            if (contentTypes.length > 0) {
                const contentType = contentTypes[0]; // application/json, multipart/form-data, etc
                
                // e.g. "users.store" -> "UsersStorePayload"
                const nameParts = operation.operationId.split('.');
                const typeName = nameParts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('') + 'Payload';
                
                content += `export type ${typeName} = operations["${operation.operationId}"]["requestBody"]["content"]["${contentType}"];\n`;
            }
        }
    }
}

fs.mkdirSync(path.dirname(modelsPath), { recursive: true });
fs.writeFileSync(modelsPath, content);

console.log(
    `[SUCCESS] Generated models.ts with ${Object.keys(schemas).length} schemas and inlined payloads.`,
);
